server:
  port: 8040
spring:
  application:
    name: gateway-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123@peer1:8761/eureka/,http://admin:123@peer2:8762/eureka/

# 解决网关超时报错的问题
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000



