server:
    port: 8083
#    context-path: /server
spring:
  profiles:
    active: dev
  application:
    name:  service-c

# 开启服务降级
feign:
  hystrix:
    enabled: true

# 定义为debug 是因为feign的logger.level 只对debug做响应
logging:
  level:
    com.yt.stude.consumer.feign: debug
