server:
    context-path: /provider/api/v1
spring:
  profiles:
    active: @profilesActive@
  application:
    name:  service-b

service-b:
  ribbon:
    # 随机策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule